# Name of the workflow
name: Lab41 TLS scanning
# How the workflow run is named in GitHub
run-name: Lab41 - ${{ github.actor }} is scanning TLS ciphers ðŸš€
permissions: read-all
# Set your preferences for the script
defaults:
  run:
    shell: pwsh
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
jobs:
  nmap-scan:
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      # Check out the git repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nmap
        run: sudo apt install nmap
      - name: Scan TLS for given domain
        run: |

          $password = "OH_NOES_EXPOSED_PASSWORD_IS_BAD"
          $httpsPort = "8001"
          Write-Host "-- Build docker"
          docker build -t vulnerable-app-image -f ./apps/vulnerable-app/Dockerfile .

          Write-host "-- Create HTTPS certificate"
          mkdir cert
          dotnet dev-certs https -ep ./cert/secret_certificate.pfx -p $password
          dotnet dev-certs https --trust

          Write-Host "-- Run docker"
          $containerId = docker run --tty --detach -p ($httpsPort+":"+$httpsPort) -e ASPNETCORE_HTTPS_PORTS=$httpsPort -e ASPNETCORE_ENVIRONMENT=Development -v ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets -v ./cert/:/https/ -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/secret_certificate.pfx -e ASPNETCORE_Kestrel__Certificates__Default__Password=$password vulnerable-app-image

          Write-Host "-- Wait for the docker for a moment"
          Start-Sleep -Seconds 10

          Write-Host "-- Fetch IP"
          $targetIp = docker inspect --format '{{ .NetworkSettings.IPAddress }}' $containerId
          Write-Host "-- TargetIP was $targetIp"
          $target = "https://"+$targetIp+":$httpsPort"

          Write-Host "-- Fetch something from target"
          curl --insecure $target

          Write-Host "-- Start TLS scan"
          $scanResults = ./scripts/tlsaudit.ps1 $targetIp $httpsPort
          $grade = $scanResults[0]
          $ciphers = $scanResults[1]

          Write-Host "---- CIPHERS ----"
          For ($i = 1; $i -le $scanResults.Length; $i++) {
            Write-Host $scanResults[$i]
          }
          Write-Host "----- GRADE -----"
          Write-Host $grade
          if ($grade -ne "A") {
            # Set proper error message
            echo "::error file=scripts/tlsaudit.ps1,title=Weak ciphers detected::Weak ciphers detected with grade: $grade"
            # Error message does not fail the job, use exit 1 to actually make it fail
            exit 1
          }
  testssl-scan:
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      # Check out the git repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan TLS for given domain
        run: |
          $password = "ANOTHER_LEAKED_PASSWORD_IS_DOUBLE_BAD"
          $httpsPort = "8001"
          Write-Host "-- Build docker"
          docker build -t vulnerable-app-image -f ./apps/vulnerable-app/Dockerfile .

          Write-host "-- Create HTTPS certificate"
          mkdir cert
          dotnet dev-certs https -ep ./cert/secret_certificate.pfx -p $password
          dotnet dev-certs https --trust

          Write-Host "-- Run docker"
          $containerId = docker run --tty --detach -p ($httpsPort+":"+$httpsPort) -e ASPNETCORE_HTTPS_PORTS=$httpsPort -e ASPNETCORE_ENVIRONMENT=Development -v ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets -v ./cert/:/https/ -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/secret_certificate.pfx -e ASPNETCORE_Kestrel__Certificates__Default__Password=$password vulnerable-app-image

          Write-Host "-- Wait for the docker for a moment"
          Start-Sleep -Seconds 10

          Write-Host "-- Fetch IP"
          $targetIp = docker inspect --format '{{ .NetworkSettings.IPAddress }}' $containerId
          Write-Host "-- TargetIP was $targetIp"
          $target = "https://"+$targetIp+":$httpsPort"

          Write-Host "-- Fetch something from target"
          curl --insecure $target

          Write-Host "-- Create results folder"
          mkdir ${{github.workspace}}/testsslreports

          Write-Host "-- Chmod results folder rights"
          chmod -R a+rw ${{github.workspace}}/testsslreports

          Write-Host "-- Start TLS scan"
          docker run --rm drwetter/testssl.sh -v ${{github.workspace}}/testsslreports:/reports:rw $target --jsonfile testsslreports --json
      - name: Upload Test results
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: testssl report
          path: ${{github.workspace}}/testsslreports
